# Generated by Django 4.2.24 on 2025-09-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status_operacional",
            field=models.CharField(
                choices=[
                    ("FUNCIONANDO", "Funcionando"),
                    ("PARCIAL", "Parcial"),
                    ("INOPERANTE", "Inoperante"),
                ],
                max_length=20,
            ),
        ),
    ]
